export const data = {
  BBRC11: "Agências de Bancos",
  BNFS11: "Agências de Bancos",
  CXAG11: "Agências de Bancos",
  TVRI11: "Agências de Bancos",
  FAED11: "Educacional",
  FCFL11: "Educacional",
  GESE11B: "Educacional",
  MINT11: "Educacional",
  RBED11: "Educacional",
  BRIM11: "Fundo de Desenvolvimento",
  BRIP11: "Fundo de Desenvolvimento",
  BTWR11: "Fundo de Desenvolvimento",
  CFHI11: "Fundo de Desenvolvimento",
  DMAC11: "Fundo de Desenvolvimento",
  EGYR11: "Fundo de Desenvolvimento",
  FLFL11: "Fundo de Desenvolvimento",
  HCST11: "Fundo de Desenvolvimento",
  HDOF11: "Fundo de Desenvolvimento",
  HRDF11: "Fundo de Desenvolvimento",
  JPPC11: "Fundo de Desenvolvimento",
  JTPR11: "Fundo de Desenvolvimento",
  KEVE11: "Fundo de Desenvolvimento",
  KINP11: "Fundo de Desenvolvimento",
  KNRE11: "Fundo de Desenvolvimento",
  LATR11B: "Fundo de Desenvolvimento",
  LOFT11B: "Fundo de Desenvolvimento",
  LUGG11: "Fundo de Desenvolvimento",
  MADS11: "Fundo de Desenvolvimento",
  MFII11: "Fundo de Desenvolvimento",
  MGIM11: "Fundo de Desenvolvimento",
  MGLC11: "Fundo de Desenvolvimento",
  NVIF11B: "Fundo de Desenvolvimento",
  ORPD11: "Fundo de Desenvolvimento",
  PABY11: "Fundo de Desenvolvimento",
  PATC11: "Fundo de Desenvolvimento",
  PNDL11: "Fundo de Desenvolvimento",
  PNPR11: "Fundo de Desenvolvimento",
  PRSN11B: "Fundo de Desenvolvimento",
  RBBV11: "Fundo de Desenvolvimento",
  RBDS11: "Fundo de Desenvolvimento",
  RBIR11: "Fundo de Desenvolvimento",
  RBRI11: "Fundo de Desenvolvimento",
  RBRM11: "Fundo de Desenvolvimento",
  RBRS11: "Fundo de Desenvolvimento",
  RBTS11: "Fundo de Desenvolvimento",
  RCFA11: "Fundo de Desenvolvimento",
  ROOF11: "Fundo de Desenvolvimento",
  RSPD11: "Fundo de Desenvolvimento",
  STRX11: "Fundo de Desenvolvimento",
  TELD11: "Fundo de Desenvolvimento",
  TGAR11: "Fundo de Desenvolvimento",
  TORM13: "Fundo de Desenvolvimento",
  TOUR11: "Fundo de Desenvolvimento",
  TRXB11: "Fundo de Desenvolvimento",
  VIDS11: "Fundo de Desenvolvimento",
  VXXV11: "Fundo de Desenvolvimento",
  YUFI11: "Fundo de Desenvolvimento",
  ZIFI11: "Fundo de Desenvolvimento",
  ALZM11: "Fundo de Fundos",
  AQLL11: "Fundo de Fundos",
  BBFO11: "Fundo de Fundos",
  BCFF11: "Fundo de Fundos",
  BCIA11: "Fundo de Fundos",
  BICE11: "Fundo de Fundos",
  BLMR11: "Fundo de Fundos",
  BPFF11: "Fundo de Fundos",
  CLIN11: "Fundo de Fundos",
  CPFF11: "Fundo de Fundos",
  CPFO11: "Fundo de Fundos",
  CRFF11: "Fundo de Fundos",
  CXRI11: "Fundo de Fundos",
  DVFF11: "Fundo de Fundos",
  FOFT11: "Fundo de Fundos",
  GCFF11: "Fundo de Fundos",
  HFOF11: "Fundo de Fundos",
  HGFF11: "Fundo de Fundos",
  IBFF11: "Fundo de Fundos",
  ITIT11: "Fundo de Fundos",
  JSAF11: "Fundo de Fundos",
  KFOF11: "Fundo de Fundos",
  KISU11: "Fundo de Fundos",
  MFAI11: "Fundo de Fundos",
  MGFF11: "Fundo de Fundos",
  MORE11: "Fundo de Fundos",
  N4V1: "Fundo de Fundos",
  OUFF11: "Fundo de Fundos",
  RBFF11: "Fundo de Fundos",
  RBRF11: "Fundo de Fundos",
  RCFF11: "Fundo de Fundos",
  RECX11: "Fundo de Fundos",
  RFOF11: "Fundo de Fundos",
  RVBI11: "Fundo de Fundos",
  SNFF11: "Fundo de Fundos",
  TCIN11: "Fundo de Fundos",
  TFOF11: "Fundo de Fundos",
  TMPS11: "Fundo de Fundos",
  VIFI11: "Fundo de Fundos",
  VTPA11: "Fundo de Fundos",
  XBXO11: "Fundo de Fundos",
  XPSF11: "Fundo de Fundos",
  HCRI11: "Hospitalar",
  HUCG11: "Hospitalar",
  HUSC11: "Hospitalar",
  HUSI11: "Hospitalar",
  NSLU11: "Hospitalar",
  NVHO11: "Hospitalar",
  BRHT11B: "Hotéis",
  BTHI11: "Hotéis",
  BTHI12: "Hotéis",
  HTMX11: "Hotéis",
  MGHT11: "Hotéis",
  RECH11: "Hotéis",
  AURB11: "Imóveis Comerciais - Outros",
  IDUA11: "Imóveis Comerciais - Outros",
  JASC11: "Imóveis Comerciais - Outros",
  JCDB11: "Imóveis Comerciais - Outros",
  LIFE11: "Imóveis Comerciais - Outros",
  SOLR11: "Imóveis Comerciais - Outros",
  TRXF11: "Imóveis Comerciais - Outros",
  ARFI11B: "Imóveis Industriais e Logísticos",
  AROA11: "Imóveis Industriais e Logísticos",
  BLCP11: "Imóveis Industriais e Logísticos",
  BLMG11: "Imóveis Industriais e Logísticos",
  BPRP11: "Imóveis Industriais e Logísticos",
  BRCO11: "Imóveis Industriais e Logísticos",
  BRLA11: "Imóveis Industriais e Logísticos",
  BTAL11: "Imóveis Industriais e Logísticos",
  BTLG11: "Imóveis Industriais e Logísticos",
  BTSG11: "Imóveis Industriais e Logísticos",
  CXTL11: "Imóveis Industriais e Logísticos",
  CYLD11: "Imóveis Industriais e Logísticos",
  EURO11: "Imóveis Industriais e Logísticos",
  FAGL11: "Imóveis Industriais e Logísticos",
  FIIB11: "Imóveis Industriais e Logísticos",
  FIIP11B: "Imóveis Industriais e Logísticos",
  FINF11: "Imóveis Industriais e Logísticos",
  GARE11: "Imóveis Industriais e Logísticos",
  GGRC11: "Imóveis Industriais e Logísticos",
  GLOG11: "Imóveis Industriais e Logísticos",
  GRLV11: "Imóveis Industriais e Logísticos",
  GTLG11: "Imóveis Industriais e Logísticos",
  HDEL11: "Imóveis Industriais e Logísticos",
  HGLG11: "Imóveis Industriais e Logísticos",
  HLOG11: "Imóveis Industriais e Logísticos",
  HSLG11: "Imóveis Industriais e Logísticos",
  KOPI11: "Imóveis Industriais e Logísticos",
  LGCP11: "Imóveis Industriais e Logísticos",
  LVBI11: "Imóveis Industriais e Logísticos",
  NEWL11: "Imóveis Industriais e Logísticos",
  OULG11: "Imóveis Industriais e Logísticos",
  PATL11: "Imóveis Industriais e Logísticos",
  PBLV11: "Imóveis Industriais e Logísticos",
  PQAG11: "Imóveis Industriais e Logísticos",
  RBLG11: "Imóveis Industriais e Logísticos",
  RBRL11: "Imóveis Industriais e Logísticos",
  RELG11: "Imóveis Industriais e Logísticos",
  RZAT11: "Imóveis Industriais e Logísticos",
  SBCL11: "Imóveis Industriais e Logísticos",
  SJAU11: "Imóveis Industriais e Logísticos",
  SNLG11: "Imóveis Industriais e Logísticos",
  TRBL11: "Imóveis Industriais e Logísticos",
  VERE11: "Imóveis Industriais e Logísticos",
  VILG11: "Imóveis Industriais e Logísticos",
  VTLT11: "Imóveis Industriais e Logísticos",
  XPIN11: "Imóveis Industriais e Logísticos",
  XPLG11: "Imóveis Industriais e Logísticos",
  APTO11: "Imóveis Residenciais",
  APXR11: "Imóveis Residenciais",
  APXU11: "Imóveis Residenciais",
  HGRS11: "Imóveis Residenciais",
  HOSI11: "Imóveis Residenciais",
  ICNE11: "Imóveis Residenciais",
  JFLL11: "Imóveis Residenciais",
  PNCR11: "Imóveis Residenciais",
  VCRR11: "Imóveis Residenciais",
  ASRF11: "Indefinido",
  ATWN11: "Indefinido",
  BIME11: "Indefinido",
  BIPD11: "Indefinido",
  BLCA11: "Indefinido",
  BRIX11: "Indefinido",
  BROL11: "Indefinido",
  BRSE11: "Indefinido",
  BTRA11: "Indefinido",
  CCLB11: "Indefinido",
  CCME11: "Indefinido",
  CFII11: "Indefinido",
  CIXR11: "Indefinido",
  CPSH11: "Indefinido",
  CSMC11: "Indefinido",
  CVPR11: "Indefinido",
  CXCI11: "Indefinido",
  CYCR11: "Indefinido",
  DPRO11: "Indefinido",
  EQIR11: "Indefinido",
  EXES11: "Indefinido",
  FARU11: "Indefinido",
  FRHY11: "Indefinido",
  GAME11: "Indefinido",
  GCOI11: "Indefinido",
  GLPL11: "Indefinido",
  GURB11: "Indefinido",
  GVBI11: "Indefinido",
  GZIT11: "Indefinido",
  HBCR11: "Indefinido",
  HCPR11: "Indefinido",
  HILG11: "Indefinido",
  IDFI11: "Indefinido",
  IRIM11: "Indefinido",
  KCRE11: "Indefinido",
  KNHF11: "Indefinido",
  KNPR11: "Indefinido",
  KNUQ11: "Indefinido",
  LAVF11: "Indefinido",
  LPLP11: "Indefinido",
  LRDI11: "Indefinido",
  MANA11: "Indefinido",
  MATV11: "Indefinido",
  MFCR11: "Indefinido",
  MGRI11: "Indefinido",
  MMPD11: "Indefinido",
  MMVE11: "Indefinido",
  OGHY11: "Indefinido",
  PCAS11: "Indefinido",
  PNLN11: "Indefinido",
  PNRC11: "Indefinido",
  QAGR11: "Indefinido",
  RBRU11: "Indefinido",
  RBRX11: "Indefinido",
  RCKF11: "Indefinido",
  RINV11: "Indefinido",
  RZDM11: "Indefinido",
  SACL11: "Indefinido",
  SEED11: "Indefinido",
  SFRO11: "Indefinido",
  SHSO11: "Indefinido",
  SIGR11: "Indefinido",
  SNEL11: "Indefinido",
  SNME11: "Indefinido",
  SPDE11: "Indefinido",
  SPMO11: "Indefinido",
  SPXS11: "Indefinido",
  SRVD11: "Indefinido",
  TELF11: "Indefinido",
  TELM11: "Indefinido",
  TJKB11: "Indefinido",
  TSNM11: "Indefinido",
  VDSV11: "Indefinido",
  VLIQ11: "Indefinido",
  VTVI11: "Indefinido",
  VVRI11: "Indefinido",
  WHGR11: "Indefinido",
  WSEC11: "Indefinido",
  ZAVI11: "Indefinido",
  AIEC11: "Lajes Corporativas",
  ALMI11: "Lajes Corporativas",
  ASMT11: "Lajes Corporativas",
  ATCR11: "Lajes Corporativas",
  BBFI11: "Lajes Corporativas",
  BLMO11: "Lajes Corporativas",
  BMII11: "Lajes Corporativas",
  BMLC11: "Lajes Corporativas",
  BRCR11: "Lajes Corporativas",
  BREV11: "Lajes Corporativas",
  BROF11: "Lajes Corporativas",
  BTML11: "Lajes Corporativas",
  CBOP11: "Lajes Corporativas",
  CENU11: "Lajes Corporativas",
  CEOC11: "Lajes Corporativas",
  CJCT11: "Lajes Corporativas",
  CNES11: "Lajes Corporativas",
  COPP11: "Lajes Corporativas",
  CTXT11: "Lajes Corporativas",
  CXCE11B: "Lajes Corporativas",
  CXCO11: "Lajes Corporativas",
  DOMC11: "Lajes Corporativas",
  DOVL11B: "Lajes Corporativas",
  DRIT11B: "Lajes Corporativas",
  DVLP11: "Lajes Corporativas",
  EDFO11B: "Lajes Corporativas",
  EDGA11: "Lajes Corporativas",
  ERPA11: "Lajes Corporativas",
  FAMB11B: "Lajes Corporativas",
  FATN11: "Lajes Corporativas",
  FCAS11: "Lajes Corporativas",
  FISC11: "Lajes Corporativas",
  FLMA11: "Lajes Corporativas",
  FMOF11: "Lajes Corporativas",
  FPAB11: "Lajes Corporativas",
  FPNG11: "Lajes Corporativas",
  FVBI11: "Lajes Corporativas",
  GTWR11: "Lajes Corporativas",
  HAAA11: "Lajes Corporativas",
  HGPO11: "Lajes Corporativas",
  HGRE11: "Lajes Corporativas",
  HOFC11: "Lajes Corporativas",
  INDE11: "Lajes Corporativas",
  KORE11: "Lajes Corporativas",
  MOFF11: "Lajes Corporativas",
  MTOF11: "Lajes Corporativas",
  NEWU11: "Lajes Corporativas",
  ONEF11: "Lajes Corporativas",
  PATB11: "Lajes Corporativas",
  PRSV11: "Lajes Corporativas",
  PVBI11: "Lajes Corporativas",
  RBOP11: "Lajes Corporativas",
  RBRP11: "Lajes Corporativas",
  RCRB11: "Lajes Corporativas",
  RDLI11: "Lajes Corporativas",
  RECT11: "Lajes Corporativas",
  RMAI11: "Lajes Corporativas",
  RNGO11: "Lajes Corporativas",
  SAIC11B: "Lajes Corporativas",
  SFND11: "Lajes Corporativas",
  SPTW11: "Lajes Corporativas",
  SPXC11: "Lajes Corporativas",
  TBOF11: "Lajes Corporativas",
  TEPP11: "Lajes Corporativas",
  THRA11: "Lajes Corporativas",
  TRNT11: "Lajes Corporativas",
  TSER11: "Lajes Corporativas",
  TSNC11: "Lajes Corporativas",
  VINO11: "Lajes Corporativas",
  VLJS11: "Lajes Corporativas",
  VLOL11: "Lajes Corporativas",
  VVCO11: "Lajes Corporativas",
  VVMR11: "Lajes Corporativas",
  XPCM11: "Lajes Corporativas",
  XPPR11: "Lajes Corporativas",
  ALZR11: "Misto",
  BLOG11: "Misto",
  BPLC11: "Misto",
  BTSI11: "Misto",
  BZEL11: "Misto",
  BZLI11: "Misto",
  CARE11: "Misto",
  CIXM11: "Misto",
  CJFI11: "Misto",
  CPLG11: "Misto",
  CPOF11: "Misto",
  CTEM11: "Misto",
  DAMA11: "Misto",
  EMET11: "Misto",
  ESTQ11: "Misto",
  EVBI11: "Misto",
  FTCE11B: "Misto",
  HGBL11: "Misto",
  HGRU11: "Misto",
  HLMB11: "Misto",
  HSRE11: "Misto",
  ICRI11: "Misto",
  IDGO11: "Misto",
  IDGR11: "Misto",
  IFRI11: "Misto",
  JCDA11: "Misto",
  JSRE11: "Misto",
  KDOL11: "Misto",
  KNRI11: "Misto",
  KRES11: "Misto",
  LAFI11: "Misto",
  LLAO11: "Misto",
  LSOI11: "Misto",
  MVFI11: "Misto",
  OPTM11: "Misto",
  OURE11: "Misto",
  PATA11: "Misto",
  PMFO11: "Misto",
  PMIS11: "Misto",
  RTEL11: "Misto",
  RZTR11: "Misto",
  RZZI11: "Misto",
  SALI11: "Misto",
  SAPI11: "Misto",
  SARE11: "Misto",
  SEQR11: "Misto",
  SNFZ11: "Misto",
  TCPF11: "Misto",
  TORD11: "Misto",
  VGHF11: "Misto",
  VGRI11: "Misto",
  VIUR11: "Misto",
  VRTM11: "Misto",
  VTXI11: "Misto",
  VVPR11: "Misto",
  WTSP11B: "Misto",
  AFHI11: "Papéis",
  ALZC11: "Papéis",
  ARRI11: "Papéis",
  ARXD11: "Papéis",
  BARI11: "Papéis",
  BBIM11: "Papéis",
  BCRI11: "Papéis",
  BICR11: "Papéis",
  BLMC11: "Papéis",
  BLUR11: "Papéis",
  BTCI11: "Papéis",
  BTCR11: "Papéis",
  CACR11: "Papéis",
  CCRF11: "Papéis",
  CPTS11: "Papéis",
  CTNP11: "Papéis",
  CVBI11: "Papéis",
  DEVA11: "Papéis",
  FISD11: "Papéis",
  FLCR11: "Papéis",
  GCRI11: "Papéis",
  HABT11: "Papéis",
  HBTT11: "Papéis",
  HCHG11: "Papéis",
  HCTR11: "Papéis",
  HGCR11: "Papéis",
  HGIC11: "Papéis",
  HREC11: "Papéis",
  HSAF11: "Papéis",
  IBCR11: "Papéis",
  IRDM11: "Papéis",
  ISCJ11: "Papéis",
  ITIP11: "Papéis",
  JBFO11: "Papéis",
  JCCJ11: "Papéis",
  JPPA11: "Papéis",
  KIVO11: "Papéis",
  KNCR11: "Papéis",
  KNHY11: "Papéis",
  KNIP11: "Papéis",
  KNSC11: "Papéis",
  LFTT11: "Papéis",
  LKDV11: "Papéis",
  LSPA11: "Papéis",
  MCCI11: "Papéis",
  MCHF11: "Papéis",
  MCHY11: "Papéis",
  MGCR11: "Papéis",
  MORC11: "Papéis",
  MTRS11: "Papéis",
  MXRF11: "Papéis",
  NAVT11: "Papéis",
  NCHB11: "Papéis",
  NCRI11: "Papéis",
  OCRE11: "Papéis",
  OUJP11: "Papéis",
  PEMA11: "Papéis",
  PLCR11: "Papéis",
  PLRI11: "Papéis",
  PORD11: "Papéis",
  PRZS11: "Papéis",
  PULV11: "Papéis",
  QAMI11: "Papéis",
  QIRI11: "Papéis",
  RBCB11: "Papéis",
  RBHG11: "Papéis",
  RBHY11: "Papéis",
  RBRR11: "Papéis",
  RBRY11: "Papéis",
  RBVO11: "Papéis",
  RCRI11B: "Papéis",
  RECR11: "Papéis",
  REIT11: "Papéis",
  RNDP11: "Papéis",
  RPRI11: "Papéis",
  RRCI11: "Papéis",
  RZAK11: "Papéis",
  SADI11: "Papéis",
  SNCI11: "Papéis",
  URPR11: "Papéis",
  VCJR11: "Papéis",
  VCRI11: "Papéis",
  VGIP11: "Papéis",
  VGIR11: "Papéis",
  VJFD11: "Papéis",
  VOTS11: "Papéis",
  VRTA11: "Papéis",
  VSEC11: "Papéis",
  VSLH11: "Papéis",
  VTPL11: "Papéis",
  VTRT11: "Papéis",
  VVCR11: "Papéis",
  XPCI11: "Papéis",
  YEES11: "Papéis",
  ABCP11: "Shoppings",
  AJFI11: "Shoppings",
  ANCR11B: "Shoppings",
  APXM11: "Shoppings",
  ATSA11: "Shoppings",
  BPML11: "Shoppings",
  DAMT11B: "Shoppings",
  ELDO11B: "Shoppings",
  FGPM11: "Shoppings",
  FIGS11: "Shoppings",
  FIVN11: "Shoppings",
  FLRP11: "Shoppings",
  FVPQ11: "Shoppings",
  GSFI11: "Shoppings",
  HGBS11: "Shoppings",
  HMOC11: "Shoppings",
  HPDP11: "Shoppings",
  HSML11: "Shoppings",
  ITRI11: "Shoppings",
  JRDM11: "Shoppings",
  LASC11: "Shoppings",
  MALL11: "Shoppings",
  MCEM11: "Shoppings",
  PQDP11: "Shoppings",
  PRTS11: "Shoppings",
  RBGS11: "Shoppings",
  SCPF11: "Shoppings",
  SHDP11B: "Shoppings",
  SHOP11: "Shoppings",
  SHPH11: "Shoppings",
  SPAF11: "Shoppings",
  SPVJ11: "Shoppings",
  VISC11: "Shoppings",
  VPSI11: "Shoppings",
  VSHO11: "Shoppings",
  WPLZ11: "Shoppings",
  XPML11: "Shoppings",
  BVAR11: "Varejo",
  DLMT11: "Varejo",
  ERCR11: "Varejo",
  MAXR11: "Varejo",
  RBRD11: "Varejo",
  RBVA11: "Varejo",
};
